description = "标仔的小空间"
mainSections = ["posts"]

colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false

customCSS = ["css/extended.css"]

enableA11y = false
enableSearch = true
enableCodeCopy = true
hotlinkFeatureImage = true

[author]
  name = "标仔"
  email = "bzone@example.com"
  headline = "记录生活，分享技术"
  bio = "这里主要写嵌入式、驱动和学习记录。"

[header]
  layout = "fixed"

[homepage]
  layout = "card"
  showRecent = true
  showRecentItems = 8
  showMoreLink = false
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  homepageImage = "images/bz.png"
  intro = "欢迎访问标仔的个人主页"

[homepage.contact]
  wechat = "htlb1214"
  phone = "134-2224-3119"

[[homepage.actionButtons]]
  label = "GitHub"
  url = "https://github.com/BiaoZai1214"
  icon = "github"

[[homepage.actionButtons]]
  label = "Bilibili"
  url = "https://space.bilibili.com/1850228834"
  icon = "bilibili"

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = true
  showWordCount = true

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  cardView = true
  cardViewScreenWidth = false
  groupByYear = false

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = false
  cardView = true

[footer]
  showMenu = true
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
