baseURL = "https://BiaoZai1214.github.io/Bzone-blog/"
title = "标仔 Blog"
theme = "blowfish"

languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
disableLanguages = ["en"]

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true
publishDir = "public"
timeZone = "Asia/Shanghai"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[build]
  writeStats = true
